HUB-411 support type hinted property added
wakeapp/dto-resolver pull request #5
Opened 2021-07-16 14:28 UTC by iskripka

2021-07-16 15:42 UTC, revilon1991 requested changes

2021-07-16 15:42 UTC, revilon1991 commented on Tests/Dto/php74/DtoResolverTraitTest.php
> +<?php
как минимум с большой буквы php74
в идеале какая-то аннотация, которая декларирует, что тест для версий php >=

2021-07-16 15:42 UTC, revilon1991 commented on Dto/DtoResolverTrait.php
> +        $data = $classVars ? get_class_vars(get_class($this)) : get_object_vars($this);
я думаю тут надо добавить метод getClassVars и вызывать в нужных местах, нужные методы.
вместо флага на аргумент

2021-07-16 15:42 UTC, revilon1991 commented on .github/workflows/tests.yaml
> +name: Test matrix
То, что это matrix видно в actions
Test matrix
=>
PHPUnit

2021-07-16 15:42 UTC, revilon1991 commented on phpunit.xml.dist
> +            <directory phpVersion="7.4" phpVersionOperator=">=">./Tests/Dto/php74</directory>
не актуально

2021-07-16 16:44 UTC, revilon1991 approved these changes

2021-07-19 09:32 UTC, kryakozyablik approved these changes

2021-07-19 09:44 UTC, iamskey requested changes
у методов toArray есть опциональный параметр - $onlyDefined. Тесты не покрывают случай, $onlyDefined = false

2021-07-20 12:26 UTC, revilon1991 commented
> у методов toArray есть опциональный параметр - $onlyDefined. Тесты не покрывают случай, $onlyDefined = false

Выяснили, что флаг не работает, если Dto создана через конструктор, поэтому оставляем "как есть" и добавляем TODO к методу toArray, а также создаем задачу на решение проблемы.

2021-07-20 12:27 UTC, iamskey approved these changes

2021-07-20 14:22 UTC, firestorm23 requested changes

2021-07-20 14:22 UTC, firestorm23 commented on Dto/DtoResolverTrait.php
> +    protected function getClassVars(): array
Почему используется конструкция

get_class_vars(get_class($this));

вместо get_object_vars($this);

либо вместо использования $this->getObjectVars()

2021-07-20 14:22 UTC, firestorm23 commented on Dto/DtoResolverTrait.php
> +    protected function getClassVars(): array
Я так понял, что именно в этом и есть изменения, почему ранее не работал type hint

2021-07-20 16:16 UTC, iskripka commented on Dto/DtoResolverTrait.php
> +    protected function getClassVars(): array
get_class_vars - возвращает все переменные объявленные в структуре класса
get_object_vars - возвращает все переменные и значения конкретного экземпляра класса

До версии 7.4 get_object_vars возвращал все переменный объявленные в классе, так как абсолютно у всех переменных было дефолтное значение null, => private $var; ($var = null)

С появлением строгой типизации переменные больше не имеют дефолтного значения, private ?string $var; ($var = UNDEFINED) при обращении к таким полям выходит эксепшн

А get_class_vars возвращает структуру класса независимо от значений в экземплярах класса

2021-07-21 09:45 UTC, firestorm23 approved these changes

2021-07-21 09:47 UTC, merged